### ISSUE TITLE
Could not use default theme if provider is not wrapped?

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [jsiebern/bs-material-ui#107]
This example here https://codesandbox.io/s/u1rq6 uses the default provider value since the theme provider component is not wrapped. How can I use the default theme provider?

**Comment by a-c-sreedhar-reddy** [comment]
The example https://material-ui.com/components/drawers/#clipped-under-the-app-bar uses `makeStyles` from 
`@material-ui/core/styles`

Where as this bindings use `makeStyles` (https://github.com/jsiebern/bs-material-ui/blame/master/public/bs-material-ui/src/MaterialUi_WithStyles.re#L22)  from 
`@material-ui/styles`

Changing it and compiling works fine.

**Comment by jsiebern** [comment]
Oh that is interesting! I wasn't aware that the style implementation didn't reference the default theme! I'll get that changed in the next update!

**Comment by a-c-sreedhar-reddy** [comment]
Linking this issue

https://github.com/mui-org/material-ui/issues/15976#issuecomment-498662233

**Comment by jsiebern** [comment]
Okay, so actually the binding into `core` rather than `styles` is already used, that's why I was confused.
Just the legacy code still holds the old path.  This is true for the `zero` branches in both ppx & bindings.

The following js gets generated:
```js
import * as Styles from "@material-ui/core/styles";

var useStyles = Styles.makeStyles({
  alignRight: {
    textAlign: "right",
    width: "100%"
  }
});
```

As this will be the new main package (and a switch to the new version despite the breaking changes will be highly recommended), I think we can close this.

**Comment by jsiebern** [comment]
This issue should be adressed with the latest package releases 😃 Please let me know if you still run into trouble with this.
